clc
clear
close all


figure;
imshow("26.jpg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("21.jpg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("24.jpg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("11.jpeg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("25.jpg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("14.jpg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("7.jpg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("20.jpg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("4.jpg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("12.jpg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("10.jpeg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("18.jpeg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("19.jpg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("15.jpg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("13.jpg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("16.jpeg.jpg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("3.jpeg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("23.jpg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("8.jpg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("22.jpg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("17.jpeg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("5.jpeg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("9.jpg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("6.jpeg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("2.jpeg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("27.jpg");
set(gcf, 'Position', get(0, 'Screensize'));
figure;
imshow("1.jpeg");
set(gcf, 'Position', get(0, 'Screensize'));